version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: build
      include: scope
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
      npm-major:
        update-types:
          - major
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    commit-message:
      prefix: build
      include: scope
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
